---
version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.4
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.routing.allocation.disk.watermark.low=1024Mb
      - cluster.routing.allocation.disk.watermark.high=512Mb
      - cluster.routing.allocation.disk.watermark.flood_stage=512Mb
    networks: ['geocloud']
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 1029:8080
    environment:
      - API_URL=http://localhost:1028/
  indexer:
    build: gributils
    image: innovationgarage/gributils
    networks: ['geocloud']
    environment:
      ESURL: "http://elasticsearch:9200"
    volumes:
      - ./gributils:/app
      - gribdata:/data
    ports:
      - "1028:1028"
  scraper-yr:
    image: innovationgarage/gributils-scraper-yr
    environment:
      INDEXURL: http://indexer:1028
    networks: ['geocloud']
  annotator:
    image: innovationgarage/gributils-annotator
    networks: ['geocloud']
    environment:
      CONFIG: |
        {
            "index": "http://indexer:1028",
            "connections": [
                {"handler": "source", "type": "listen", "address": "tcp:1024"},
                {"handler": "destination", "type": "listen", "address": "tcp:1025"}
            ]
        }
    ports:
      - "7024:1024"
      - "7025:1025"

networks:
  geocloud:
    driver: bridge

volumes:
  gribdata:
    driver: local
  esdata:
    driver: local
